[package]
name = "audio-test2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
nannou_audio = "0.18"
ringbuf = "0.2.2"
rustfft = "6.1.0"
spectrum-analyzer = "1.2.6"